# Generated by Django 4.1 on 2022-08-20 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='authormodel',
            managers=[
            ],
        ),
    ]
