# Generated by Django 4.1 on 2022-08-21 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_bookmodel_isbn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmodel',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
